apiVersion: apps/v1
kind: Deployment
metadata:
  name: sense-voice
  namespace: default
  labels:
    app: sense-voice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sense-voice
  template:
    metadata:
      labels:
        app: sense-voice
    spec:
      containers:
      - name: sense-voice
        image: xxxxxx/agent/sense-voice-api:arm64-9a358d5f-2025-05-07-18-46-55
        imagePullPolicy: IfNotPresent
        env:
        - name: model_path
          value: /mnt/tensorbee/models/BAAI/SenseVoiceSmall
        ports:
        - containerPort: 8003
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 90
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 90
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 120
          periodSeconds: 10
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
            cpu: "2"
            memory: 4Gi
        volumeMounts:
        - name: model-storage
          mountPath: /mnt/tensorbee/models
      nodeSelector:
        kubernetes.io/hostname: k3s-master-2
      volumes:
      - name: model-storage
        hostPath:
          path: /mnt/tensorbee/models
---
apiVersion: v1
kind: Service
metadata:
  name: sense-voice-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: sense-voice
  ports:
  - name: http
    port: 8003
    targetPort: 8003
    nodePort: 30003
